# Generated by Django 5.2 on 2025-05-01 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ediciones', to='noticias.noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('modificada', 'Pendiente de Edición')], default='pendiente', max_length=20),
        ),
    ]
