# Generated by Django 5.2 on 2025-05-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_noticia_original_alter_noticia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='justificacion_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
